apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: frontend
spec:
  replicas: 3  # Fixed typo
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: app1
          image: ganesh6498/flask_app_db_kub:latest
          ports:
            - containerPort: 5000  # Fixed key name
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_HOST
              value: "backend-service"
            - name: POSTGRES_PORT
              value: "5432"

---


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
